platform :ios, '9.0'

workspace '../SwiftyDemo.xcworkspace'

def app_pods
    pod 'Visuality', '5.4.1'
    pod 'Direct', '1.6'
    pod 'Pixels', '1.4'
    pod 'AlamofireImage'
    pod 'Moya', '11.0.2'
    pod 'PinLayout', '1.7.9'
end

def test_pods
    pod 'Quick', '1.3.1'
    pod 'Nimble', '7.1.3'
end

target 'SwiftyDemo' do
    use_frameworks!
    app_pods
    
    target 'SwiftyDemoTests' do
        inherit! :search_paths
        app_pods
        test_pods
    end
    
end
